version: '3.8'

services:
  # Servicio de la aplicación
  cinemagic-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=cinemagic-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=cine
    depends_on:
      - cinemagic-db
    volumes:
      - .:/app
    restart: unless-stopped

  # Servicio de MySQL
  cinemagic-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cine
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data: